<?php

namespace KH\Planner\Agents;

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * ExportAgent
 * 
 * Replaces the legacy Framework_Generator_Exporter.
 * Handles exporting session dossier/briefs to DOCX and HTML formats.
 */
class ExportAgent {

    const EXPORT_DIR = 'editorial_exports';

    /**
     * Export session brief to DOCX
     */
    public function export_to_docx( $post_id ) {
        $post = get_post( $post_id );
        if ( ! $post || $post->post_type !== 'planner_session' ) {
            return new \WP_Error( 'invalid_session', 'Invalid session ID' );
        }

        if ( ! class_exists( 'PhpOffice\\PhpWord\\PhpWord' ) ) {
            return new \WP_Error( 'phpword_not_found', 'PHPWord library not available. Please ensure it is installed.' );
        }

        $phpWord = new \PhpOffice\PhpWord\PhpWord();
        $section = $phpWord->addSection();

        $section->addTitle( $post->post_title, 1 );
        $section->addText( 'Generated by Touchpoint Editorial Planner' );
        $section->addText( 'Created: ' . current_time( 'F j, Y' ) );
        $section->addPageBreak();

        // Retrieve Phase Data
        $phase1 = get_post_meta( $post_id, 'kh_planner_phase1_result', true );
        $phase2 = get_post_meta( $post_id, 'kh_planner_phase2_result', true );
        $phase3 = get_post_meta( $post_id, 'kh_planner_phase3_result', true );
        $synopses = get_post_meta( $post_id, 'kh_planner_final_synopses', true );

        if ( ! empty( $phase1['executive_summary'] ) ) {
            $section->addTitle( 'Phase 1: Discovery Summary', 2 );
            $section->addText( $phase1['executive_summary'] );
            
            if ( ! empty( $phase1['trends'] ) ) {
                $section->addTitle( 'Key Trends Identified', 3 );
                foreach ( $phase1['trends'] as $trend ) {
                    $title = $trend['title'] ?? 'Untitled';
                    $why = $trend['why_it_matters'] ?? '';
                    $section->addText( "• {$title}: {$why}" );
                }
            }
            $section->addTextBreak(1);
        }

        if ( ! empty( $phase2['ranked_keywords'] ) ) {
            $section->addTitle( 'Phase 2: Strategic Keywords', 2 );
            $table = $section->addTable(['borderSize' => 6, 'borderColor' => '999999']);
            $table->addRow();
            $table->addCell(4000)->addText('Keyword', ['bold' => true]);
            $table->addCell(2000)->addText('Volume', ['bold' => true]);
            $table->addCell(2000)->addText('Priority', ['bold' => true]);
            
            foreach ( array_slice( $phase2['ranked_keywords'], 0, 10 ) as $kw ) {
                $table->addRow();
                $table->addCell(4000)->addText( $kw['keyword'] );
                $table->addCell(2000)->addText( $kw['search_volume'] ?? 'N/A' );
                $table->addCell(2000)->addText( $kw['priority_score'] ?? '0' );
            }
            $section->addTextBreak(1);
        }

        if ( ! empty( $phase3['prioritized_topics'] ) ) {
            $section->addTitle( 'Phase 3: Topic Framing', 2 );
            foreach ( $phase3['prioritized_topics'] as $topic ) {
                $section->addTitle( $topic['topic'], 3 );
                $section->addText( "Strategic Intent: " . ( $topic['why_now'] ?? '' ), ['bold' => true] );
                
                if ( ! empty( $topic['key_findings'] ) ) {
                    $section->addText( "Key Findings:", ['bold' => true] );
                    foreach ( $topic['key_findings'] as $finding ) {
                        $section->addText( "• {$finding}" );
                    }
                }
            }
            $section->addTextBreak(1);
        }

        if ( ! empty( $synopses['synopses'] ) ) {
            $section->addTitle( 'Final Article Synopses', 2 );
            foreach ( $synopses['synopses'] as $s ) {
                $headline = $s['headline'] ?? 'Untitled';
                $section->addTitle( "ARTICLE: {$headline}", 3 );
                $section->addText( "Summary: " . ( $s['summary'] ?? '' ) );
                
                if ( ! empty( $s['key_points'] ) ) {
                    $section->addText( "Key Points:", ['bold' => true] );
                    foreach ( (array) $s['key_points'] as $kp ) {
                        $section->addText( "• {$kp}" );
                    }
                }
                $section->addTextBreak(1);
            }
        }

        // Provenance Appendix
        $this->add_provenance_appendix_docx( $section, $post_id );

        $filename = 'session-' . $post_id . '-' . date('Y-m-d-H-i-s') . '.docx';
        $filepath = $this->get_export_path( $filename );

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter( $phpWord, 'Word2007' );
        $objWriter->save( $filepath );

        $file_url = $this->get_export_url( $filename );
        update_post_meta( $post_id, 'kh_planner_export_docx_url', $file_url );

        return [
            'file_url' => $file_url,
            'file_path' => $filepath,
            'filename' => $filename,
        ];
    }

    /**
     * Export session brief to HTML
     */
    public function export_to_html( $post_id ) {
        $post = get_post( $post_id );
        if ( ! $post || $post->post_type !== 'planner_session' ) {
            return new \WP_Error( 'invalid_session', 'Invalid session ID' );
        }

        $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>' . esc_html( $post->post_title ) . '</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; margin: 40px auto; max-width: 800px; padding: 20px; color: #333; }
        h1 { color: #111; border-bottom: 2px solid #111; padding-bottom: 10px; }
        h2 { color: #444; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        h3 { color: #666; }
        .meta { color: #888; font-size: 0.9em; margin-bottom: 30px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; margin-bottom: 20px; }
        th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
        th { background-color: #f9f9f9; }
        .section { margin-bottom: 30px; }
        .synopsis-card { background: #f9f9f9; padding: 20px; margin-bottom: 20px; border-left: 4px solid #333; }
        .provenance { background: #f4f4f4; padding: 20px; margin-top: 40px; border-left: 4px solid #2c5f2d; }
        .citation { margin: 15px 0; padding: 15px; background: white; border: 1px solid #ddd; border-radius: 4px; }
        .citation h3 { margin-top: 0; }
    </style>
</head>
<body>
    <h1>' . esc_html( $post->post_title ) . '</h1>
    <div class="meta">
        Generated by Touchpoint Editorial Planner<br>
        Created: ' . current_time( 'F j, Y' ) . '
    </div>';

        $phase1 = get_post_meta( $post_id, 'kh_planner_phase1_result', true );
        $phase2 = get_post_meta( $post_id, 'kh_planner_phase2_result', true );
        $phase3 = get_post_meta( $post_id, 'kh_planner_phase3_result', true );
        $synopses = get_post_meta( $post_id, 'kh_planner_final_synopses', true );

        if ( ! empty( $phase1['executive_summary'] ) ) {
            $html .= '<h2>Phase 1: Discovery Summary</h2>';
            $html .= '<div class="section"><p>' . nl2br( esc_html( $phase1['executive_summary'] ) ) . '</p>';
            
            if ( ! empty( $phase1['trends'] ) ) {
                $html .= '<h3>Key Trends Identified</h3><ul>';
                foreach ( $phase1['trends'] as $trend ) {
                    $html .= '<li><strong>' . esc_html( $trend['title'] ?? 'Untitled' ) . ':</strong> ' . esc_html( $trend['why_it_matters'] ?? '' ) . '</li>';
                }
                $html .= '</ul>';
            }
            $html .= '</div>';
        }

        if ( ! empty( $phase2['ranked_keywords'] ) ) {
            $html .= '<h2>Phase 2: Strategic Keywords</h2>';
            $html .= '<div class="section"><table><thead><tr><th>Keyword</th><th>Volume</th><th>Priority</th></tr></thead><tbody>';
            foreach ( array_slice( $phase2['ranked_keywords'], 0, 10 ) as $kw ) {
                $html .= '<tr>';
                $html .= '<td>' . esc_html( $kw['keyword'] ) . '</td>';
                $html .= '<td>' . esc_html( $kw['search_volume'] ?? 'N/A' ) . '</td>';
                $html .= '<td>' . esc_html( $kw['priority_score'] ?? '0' ) . '</td>';
                $html .= '</tr>';
            }
            $html .= '</tbody></table></div>';
        }

        if ( ! empty( $phase3['prioritized_topics'] ) ) {
            $html .= '<h2>Phase 3: Topic Framing</h2><div class="section">';
            foreach ( $phase3['prioritized_topics'] as $topic ) {
                $html .= '<h3>' . esc_html( $topic['topic'] ) . '</h3>';
                $html .= '<p><strong>Strategic Intent:</strong> ' . esc_html( $topic['why_now'] ?? '' ) . '</p>';
                if ( ! empty( $topic['key_findings'] ) ) {
                    $html .= '<p><strong>Key Findings:</strong></p><ul>';
                    foreach ( $topic['key_findings'] as $finding ) {
                        $html .= '<li>' . esc_html( $finding ) . '</li>';
                    }
                    $html .= '</ul>';
                }
            }
            $html .= '</div>';
        }

        if ( ! empty( $synopses['synopses'] ) ) {
            $html .= '<h2>Final Article Synopses</h2><div class="section">';
            foreach ( $synopses['synopses'] as $s ) {
                $html .= '<div class="synopsis-card">';
                $html .= '<h3>ARTICLE: ' . esc_html( $s['headline'] ?? 'Untitled' ) . '</h3>';
                $html .= '<p><strong>Summary:</strong> ' . esc_html( $s['summary'] ?? '' ) . '</p>';
                if ( ! empty( $s['key_points'] ) ) {
                    $html .= '<p><strong>Key Points:</strong></p><ul>';
                    foreach ( (array) $s['key_points'] as $kp ) {
                        $html .= '<li>' . esc_html( $kp ) . '</li>';
                    }
                    $html .= '</ul>';
                }
                $html .= '</div>';
            }
            $html .= '</div>';
        }

        // Provenance Appendix (inside body, before closing tags)
        $html .= $this->generate_provenance_appendix_html( $post_id );

        $html .= '
</body>
</html>';

        $filename = 'session-' . $post_id . '-' . date('Y-m-d-H-i-s') . '.html';
        $filepath = $this->get_export_path( $filename );

        file_put_contents( $filepath, $html );
        $file_url = $this->get_export_url( $filename );

        update_post_meta( $post_id, 'kh_planner_export_html_url', $file_url );

        return [
            'file_url' => $file_url,
            'file_path' => $filepath,
            'filename' => $filename,
        ];
    }

    // -------------------------------------------------------------------------
    //  Provenance Appendix (citations from DB)
    // -------------------------------------------------------------------------

    /**
     * Add provenance appendix to DOCX export.
     * Shows each verified citation with tier, authority score, and APA string.
     */
    private function add_provenance_appendix_docx( $section, $post_id ) {
        $citations = $this->get_citations_for_export( $post_id );
        if ( empty( $citations ) ) {
            return;
        }

        $section->addPageBreak();
        $section->addTitle( 'Provenance Appendix', 1 );
        $section->addText( 'This appendix contains the verified source citations used to inform this framework, ordered by authority score.' );
        $section->addTextBreak(1);

        foreach ( $citations as $citation ) {
            $section->addTitle( $citation['title'] ?? 'Untitled', 3 );

            if ( ! empty( $citation['apa_string'] ) && $citation['apa_string'] !== 'details_unavailable' ) {
                $section->addText( 'APA: ' . $citation['apa_string'] );
            }

            $section->addText( 'Source: ' . ( $citation['url'] ?? '' ) );
            $section->addText( 'Tier: ' . ( $citation['tier'] ?? 'tier3' ) );
            $section->addText( 'Authority Score: ' . number_format( (float) ( $citation['authority_score'] ?? 0.5 ), 2 ) );

            $author = $citation['lead_author'] ?? '';
            $pub    = $citation['publication'] ?? '';
            if ( $author || $pub ) {
                $section->addText( 'Author: ' . $author . ( $pub ? ' | Publication: ' . $pub : '' ) );
            }

            $section->addTextBreak(1);
        }
    }

    /**
     * Generate provenance appendix for HTML export.
     */
    private function generate_provenance_appendix_html( $post_id ) {
        $citations = $this->get_citations_for_export( $post_id );
        if ( empty( $citations ) ) {
            return '';
        }

        $html = '
    <div class="provenance">
        <h2>Provenance Appendix</h2>
        <p>This appendix contains the verified source citations used to inform this framework, ordered by authority score.</p>';

        foreach ( $citations as $citation ) {
            $html .= '
        <div class="citation">
            <h3>' . esc_html( $citation['title'] ?? 'Untitled' ) . '</h3>';

            if ( ! empty( $citation['apa_string'] ) && $citation['apa_string'] !== 'details_unavailable' ) {
                $html .= '<p><strong>APA:</strong> ' . esc_html( $citation['apa_string'] ) . '</p>';
            }

            $html .= '<p><strong>Source:</strong> <a href="' . esc_url( $citation['url'] ?? '' ) . '">' . esc_html( $citation['url'] ?? '' ) . '</a></p>';
            $html .= '<p><strong>Tier:</strong> ' . esc_html( $citation['tier'] ?? 'tier3' ) . ' | <strong>Authority Score:</strong> ' . esc_html( number_format( (float) ( $citation['authority_score'] ?? 0.5 ), 2 ) ) . '</p>';

            $author = $citation['lead_author'] ?? '';
            $pub    = $citation['publication'] ?? '';
            if ( $author || $pub ) {
                $html .= '<p><strong>Author:</strong> ' . esc_html( $author ) . ( $pub ? ' | <strong>Publication:</strong> ' . esc_html( $pub ) : '' ) . '</p>';
            }

            $html .= '
        </div>';
        }

        $html .= '
    </div>';

        return $html;
    }

    /**
     * Get citations for the export — tries the CitationStore first,
     * falls back to the brief's stored citation IDs.
     */
    private function get_citations_for_export( $post_id ) {
        // Try CitationStore first
        if ( class_exists( '\\KH\\Planner\\Core\\CitationStore' ) ) {
            $store = new \KH\Planner\Core\CitationStore();
            $citations = $store->get_citations_by_session( $post_id, false );
            if ( ! empty( $citations ) ) {
                return $citations;
            }
        }

        // Fallback: try brief's citation data
        $brief_id = get_post_meta( $post_id, 'kh_planner_brief_id', true );
        if ( $brief_id && class_exists( '\\KH\\Planner\\Core\\CitationStore' ) ) {
            $store = new \KH\Planner\Core\CitationStore();
            return $store->get_citations_by_brief( $brief_id );
        }

        return [];
    }

    private function get_export_path( $filename ) {
        $upload_dir = wp_upload_dir();
        $export_dir = $upload_dir['basedir'] . '/' . self::EXPORT_DIR;
        if ( ! file_exists( $export_dir ) ) {
            wp_mkdir_p( $export_dir );
        }
        return $export_dir . '/' . $filename;
    }

    private function get_export_url( $filename ) {
        $upload_dir = wp_upload_dir();
        return $upload_dir['baseurl'] . '/' . self::EXPORT_DIR . '/' . $filename;
    }

    /**
     * Export a single article's framework to HTML.
     *
     * Loads the framework output from session meta for the given article,
     * generates a self-contained HTML document, and saves it to the export
     * directory.  Returns the file URL and path so the frontend can present
     * a download link or open the file directly.
     *
     * @param int    $post_id    Planner session ID.
     * @param string $article_id Article ID from session meta.
     * @return array|\WP_Error
     */
    public function export_framework_to_html( $post_id, $article_id ) {
        $post = get_post( $post_id );
        if ( ! $post || $post->post_type !== 'planner_session' ) {
            return new \WP_Error( 'invalid_session', 'Invalid session ID' );
        }

        // Load the framework from session meta
        $framework = $this->get_article_framework( $post_id, $article_id );
        if ( is_wp_error( $framework ) ) {
            return $framework;
        }

        $article_title = $framework['article_title'] ?? $framework['title'] ?? 'Framework';
        $output        = $framework['output'] ?? [];

        // Build the HTML document
        $html = '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>' . esc_html( $article_title ) . ' — Framework Export</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; margin: 40px auto; max-width: 800px; padding: 20px; color: #333; }
        h1 { color: #111; border-bottom: 2px solid #111; padding-bottom: 10px; }
        h2 { color: #444; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        h3 { color: #555; margin-top: 20px; }
        .meta { color: #888; font-size: 0.9em; margin-bottom: 30px; }
        .section { margin-bottom: 30px; }
        .observation { background: #f9f9f9; padding: 16px; margin-bottom: 12px; border-left: 3px solid #2271b1; border-radius: 0 4px 4px 0; }
        .observation h4 { margin: 0 0 6px; font-size: 1em; }
        .evidence { font-size: 0.85em; color: #666; margin-top: 6px; padding: 8px; background: #fff; border: 1px solid #eee; border-radius: 3px; }
        .citation { margin: 12px 0; padding: 12px; background: #fff; border: 1px solid #ddd; border-radius: 4px; }
        .citation .apa { font-style: italic; color: #555; }
        .citation .meta { font-size: 0.85em; color: #888; margin: 4px 0 0; }
        .theme-list { list-style: none; padding: 0; }
        .theme-list li { display: inline-block; background: #e8f0fe; padding: 4px 12px; margin: 3px; border-radius: 12px; font-size: 0.9em; }
        .scoring { display: flex; gap: 20px; flex-wrap: wrap; }
        .score-badge { display: inline-block; padding: 6px 16px; border-radius: 20px; font-weight: 600; }
        .score-excellent { background: #edfaef; color: #1e7e34; }
        .score-good { background: #e7f5ff; color: #0c5460; }
        .score-standard { background: #fffbe6; color: #7d6608; }
        ul { padding-left: 20px; }
    </style>
</head>
<body>
    <h1>' . esc_html( $article_title ) . '</h1>
    <div class="meta">
        Generated by Touchpoint Editorial Planner<br>
        Session: ' . esc_html( $post->post_title ) . '<br>
        Exported: ' . current_time( 'F j, Y' ) . '
    </div>';

        // --- Overview ---
        if ( ! empty( $output['overview'] ) ) {
            $html .= '<div class="section"><h2>Overview</h2><p>' . esc_html( $output['overview'] ) . '</p></div>';
        }

        // --- Context ---
        if ( ! empty( $output['context'] ) ) {
            $html .= '<div class="section"><h2>Context</h2><p>' . esc_html( $output['context'] ) . '</p></div>';
        }

        // --- Application ---
        if ( ! empty( $output['application'] ) ) {
            $html .= '<div class="section"><h2>Application</h2>';
            if ( ! empty( $output['application']['intended_reader'] ) ) {
                $html .= '<p><strong>Intended Reader:</strong> ' . esc_html( $output['application']['intended_reader'] ) . '</p>';
            }
            if ( ! empty( $output['application']['use_case'] ) ) {
                $html .= '<p><strong>Use Case:</strong> ' . esc_html( $output['application']['use_case'] ) . '</p>';
            }
            $html .= '</div>';
        }

        // --- Observations ---
        if ( ! empty( $output['observations'] ) && is_array( $output['observations'] ) ) {
            $html .= '<div class="section"><h2>Observations</h2>';
            foreach ( $output['observations'] as $obs ) {
                $html .= '<div class="observation">';
                $html .= '<h4>' . esc_html( $obs['headline'] ?? 'Observation' ) . '</h4>';
                if ( ! empty( $obs['detail'] ) ) {
                    $html .= '<p>' . esc_html( $obs['detail'] ) . '</p>';
                }
                // Evidence
                if ( ! empty( $obs['evidence'] ) && is_array( $obs['evidence'] ) ) {
                    foreach ( $obs['evidence'] as $ev ) {
                        $html .= '<div class="evidence">';
                        if ( ! empty( $ev['passage_snippet'] ) ) {
                            $html .= '<em>"' . esc_html( $ev['passage_snippet'] ) . '"</em>';
                        }
                        if ( isset( $ev['citation_index'] ) ) {
                            $html .= ' <span style="color:#888;">[Source ' . (int) $ev['citation_index'] . ']</span>';
                        }
                        if ( isset( $ev['confidence'] ) ) {
                            $html .= ' <span style="color:#888;">Confidence: ' . esc_html( number_format( (float) $ev['confidence'] * 100, 0 ) ) . '%</span>';
                        }
                        $html .= '</div>';
                    }
                }
                $html .= '</div>';
            }
            $html .= '</div>';
        }

        // --- Key Themes ---
        if ( ! empty( $output['key_themes'] ) && is_array( $output['key_themes'] ) ) {
            $html .= '<div class="section"><h2>Key Themes</h2><ul class="theme-list">';
            foreach ( $output['key_themes'] as $theme ) {
                $html .= '<li>' . esc_html( $theme ) . '</li>';
            }
            $html .= '</ul></div>';
        }

        // --- Writer Guidance ---
        if ( ! empty( $output['writer_guidance'] ) ) {
            $html .= '<div class="section"><h2>Writer Guidance</h2>';
            if ( ! empty( $output['writer_guidance']['tone'] ) ) {
                $html .= '<p><strong>Tone:</strong> ' . esc_html( $output['writer_guidance']['tone'] ) . '</p>';
            }
            if ( ! empty( $output['writer_guidance']['structure'] ) ) {
                $html .= '<p><strong>Structure:</strong> ' . esc_html( $output['writer_guidance']['structure'] ) . '</p>';
            }
            if ( ! empty( $output['writer_guidance']['target_audience_notes'] ) ) {
                $html .= '<p><strong>Audience Notes:</strong> ' . esc_html( $output['writer_guidance']['target_audience_notes'] ) . '</p>';
            }
            if ( ! empty( $output['writer_guidance']['citation_usage'] ) ) {
                $html .= '<p><strong>Citation Usage:</strong> ' . esc_html( $output['writer_guidance']['citation_usage'] ) . '</p>';
            }
            if ( ! empty( $output['writer_guidance']['key_messages'] ) && is_array( $output['writer_guidance']['key_messages'] ) ) {
                $html .= '<p><strong>Key Messages:</strong></p><ul>';
                foreach ( $output['writer_guidance']['key_messages'] as $msg ) {
                    $html .= '<li>' . esc_html( $msg ) . '</li>';
                }
                $html .= '</ul>';
            }
            $html .= '</div>';
        }

        // --- Scoring ---
        if ( ! empty( $output['scoring'] ) ) {
            $quality = $output['scoring']['quality_level'] ?? '';
            $score_class = 'score-standard';
            if ( $quality === 'excellent' ) {
                $score_class = 'score-excellent';
            } elseif ( $quality === 'good' ) {
                $score_class = 'score-good';
            }
            $html .= '<div class="section"><h2>Quality Assessment</h2>';
            $html .= '<div class="scoring">';
            $html .= '<span class="score-badge ' . $score_class . '">' . esc_html( ucfirst( $quality ) ) . '</span>';
            if ( isset( $output['scoring']['total_score'] ) ) {
                $html .= '<span><strong>Score:</strong> ' . (int) $output['scoring']['total_score'] . '/100</span>';
            }
            if ( isset( $output['scoring']['is_publishable'] ) ) {
                $html .= '<span><strong>' . ( $output['scoring']['is_publishable'] ? '✓ Publishable' : '✗ Needs Revision' ) . '</strong></span>';
            }
            $html .= '</div></div>';
        }

        // --- Citations ---
        if ( ! empty( $output['citations'] ) && is_array( $output['citations'] ) ) {
            $html .= '<div class="section"><h2>Citations (' . count( $output['citations'] ) . ' sources)</h2>';
            foreach ( $output['citations'] as $citation ) {
                $html .= '<div class="citation">';
                if ( ! empty( $citation['apa'] ) ) {
                    $html .= '<div class="apa">' . esc_html( $citation['apa'] ) . '</div>';
                } elseif ( ! empty( $citation['title'] ) ) {
                    $html .= '<strong>' . esc_html( $citation['title'] ) . '</strong>';
                }
                if ( ! empty( $citation['url'] ) ) {
                    $html .= '<br><a href="' . esc_url( $citation['url'] ) . '">' . esc_html( $citation['url'] ) . '</a>';
                }
                $meta_parts = [];
                if ( ! empty( $citation['lead_author'] ) ) $meta_parts[] = $citation['lead_author'];
                if ( ! empty( $citation['organisation'] ) ) $meta_parts[] = $citation['organisation'];
                if ( ! empty( $citation['publication_date'] ) ) $meta_parts[] = $citation['publication_date'];
                if ( ! empty( $meta_parts ) ) {
                    $html .= '<div class="meta">' . esc_html( implode( ' · ', $meta_parts ) ) . '</div>';
                }
                if ( ! empty( $citation['passage_snippet'] ) ) {
                    $html .= '<p style="font-size:0.9em;color:#555;"><em>"' . esc_html( $citation['passage_snippet'] ) . '"</em></p>';
                }
                if ( ! empty( $citation['relevance'] ) ) {
                    $html .= '<p style="font-size:0.9em;color:#555;">' . esc_html( $citation['relevance'] ) . '</p>';
                }
                $html .= '</div>';
            }
            $html .= '</div>';
        }

        $html .= '
</body>
</html>';

        $sanitized_title = sanitize_title( $article_title );
        $filename = 'framework-' . $sanitized_title . '-' . date('Y-m-d-H-i-s') . '.html';
        $filepath = $this->get_export_path( $filename );

        file_put_contents( $filepath, $html );
        $file_url = $this->get_export_url( $filename );

        update_post_meta( $post_id, 'kh_planner_export_framework_url', $file_url );

        return [
            'file_url'  => $file_url,
            'file_path' => $filepath,
            'filename'  => $filename,
            'article_id' => $article_id,
            'title'     => $article_title,
        ];
    }

    /**
     * Export a single article's framework to JSON.
     *
     * Saves the raw framework output as a formatted JSON file.
     *
     * @param int    $post_id    Planner session ID.
     * @param string $article_id Article ID from session meta.
     * @return array|\WP_Error
     */
    public function export_framework_to_json( $post_id, $article_id ) {
        $framework = $this->get_article_framework( $post_id, $article_id );
        if ( is_wp_error( $framework ) ) {
            return $framework;
        }

        $article_title = $framework['article_title'] ?? $framework['title'] ?? 'Framework';
        $sanitized_title = sanitize_title( $article_title );
        $filename = 'framework-' . $sanitized_title . '-' . date('Y-m-d-H-i-s') . '.json';
        $filepath = $this->get_export_path( $filename );

        $json_content = wp_json_encode( $framework, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );
        file_put_contents( $filepath, $json_content );
        $file_url = $this->get_export_url( $filename );

        update_post_meta( $post_id, 'kh_planner_export_framework_json_url', $file_url );

        return [
            'file_url'  => $file_url,
            'file_path' => $filepath,
            'filename'  => $filename,
            'article_id' => $article_id,
            'title'     => $article_title,
        ];
    }

    /**
     * Retrieve the framework output for a specific article from session meta.
     *
     * @param int    $post_id    Planner session ID.
     * @param string $article_id Article ID from session meta.
     * @return array|\WP_Error
     */
    private function get_article_framework( $post_id, $article_id ) {
        $meta_raw = get_post_meta( $post_id, 'kh_planner_meta', true );
        if ( is_array( $meta_raw ) ) {
            $meta = $meta_raw;
        } elseif ( is_string( $meta_raw ) && $meta_raw !== '' ) {
            $meta = json_decode( $meta_raw, true );
            if ( json_last_error() !== JSON_ERROR_NONE || ! is_array( $meta ) ) {
                $meta = [];
            }
        } else {
            $meta = [];
        }

        $articles = $meta['articles'] ?? [];
        $article = null;
        foreach ( $articles as $a ) {
            if ( ( $a['id'] ?? '' ) === $article_id ) {
                $article = $a;
                break;
            }
        }

        if ( ! $article ) {
            return new \WP_Error( 'article_not_found', 'Article not found in session meta.' );
        }

        if ( empty( $article['framework']['output'] ) ) {
            return new \WP_Error( 'no_framework', 'No framework output available for this article.' );
        }

        return [
            'article_title' => $article['headline'] ?? $article['title'] ?? '',
            'article_id'    => $article_id,
            'output'        => $article['framework']['output'],
            'status'        => $article['framework']['status'] ?? 'unknown',
        ];
    }
}
